#!/usr/bin/env python3
"""Generate LaTeX annotation-scheme table from coding_Q4.csv."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_INPUT = Path("human_eval/annotations/coding_Q4.csv")
DEFAULT_OUTPUT = Path("analysis/manuscript_tables/tex/annotation_scheme_Q4.tex")

CODE_RE = re.compile(r"^(M\d+)\.\s*(.+)$")

ABBREV_FOLLOW = ("e.g.", "i.e.", "etc.", "vs.", "cf.")

ROW_END = r"\\[5pt]"
ARRAY_STRETCH = "1.75"


@dataclass
class CodeRow:
    code: str
    aspect: str
    definition: str
    ai_examples: str
    human_examples: str


def latex_escape(text: str) -> str:
    """Escape text for LaTeX tabular cells (not math mode)."""
    if not text:
        return ""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\^{}"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    text = re.sub(r'"([^"]*)"', r"``\1''", text)
    text = text.replace('"', "''")
    text = text.replace("\u2014", "---")
    text = text.replace("\u2013", "--")
    text = text.replace("\u2026", r"\ldots{}")
    text = text.replace("→", r"$\rightarrow$")
    text = text.replace("…", r"\ldots{}")
    text = text.replace("clichéd", r"clich\'{e}d")
    text = text.replace("cliché", r"clich\'{e}")
    return " ".join(text.split())


def add_abbrev_line_breaks(text: str) -> str:
    for abbrev in ABBREV_FOLLOW:
        text = text.replace(abbrev + " ", abbrev + r"\ ")
    return text


def latex_cell(text: str) -> str:
    return add_abbrev_line_breaks(latex_escape(text))


def parse_csv(path: Path) -> list[CodeRow]:
    codes: list[CodeRow] = []

    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader, None)
        if header is None:
            raise ValueError(f"Empty CSV: {path}")

        for row in reader:
            if not row or all(not cell.strip() for cell in row):
                continue

            first = row[0].strip()
            if not first or first.upper().startswith("NOTE"):
                continue

            match = CODE_RE.match(first)
            if match is None:
                continue

            code, aspect = match.group(1), match.group(2).strip()
            definition = row[1].strip() if len(row) > 1 else ""
            ai_examples = row[2].strip() if len(row) > 2 else ""
            human_examples = row[3].strip() if len(row) > 3 else ""

            codes.append(
                CodeRow(
                    code=code,
                    aspect=aspect,
                    definition=definition,
                    ai_examples=ai_examples,
                    human_examples=human_examples,
                )
            )

    if not codes:
        raise ValueError(f"No code rows parsed from {path}")

    return codes


def render_code_rows(codes: list[CodeRow]) -> list[str]:
    lines: list[str] = []
    for code in codes:
        lines.append(
            f"        \\codelabel{{{code.code}}} & " # \codelabel should be defined in main latex file
            f"{latex_cell(code.aspect)} &\n"
            f"        {latex_cell(code.definition)} &\n"
            f"        {latex_cell(code.ai_examples)} &\n"
            f"        {latex_cell(code.human_examples)} {ROW_END}"
        )
    return lines


TABLE_HEADER = (
    r"        \toprule"
    "\n"
    r"        \textbf{Code} & \textbf{Aspect} & \textbf{Definition (AI-pointing)} & \textbf{Human-pointing examples} \\"
    "\n"
    r"        \midrule"
)
TABLE_CONTINUED_HEAD = (
    r"        \multicolumn{5}{c}{\textbf{Table \thetable{} -- continued from previous page}} \\"
    "\n"
    + TABLE_HEADER
)
TABLE_CONTINUED_FOOT = (
    r"        \midrule"
    "\n"
    r"        \multicolumn{5}{r}{\textit{Continued on next page}} \\"
    "\n"
    r"        \midrule"
)
TABLE_LAST_FOOT = (
    r"        \bottomrule"
    "\n"
    r"        \noalign{\vskip 0.75em}"
    "\n"
    r"        \caption{CPTN_PLACEHOLDER}"
    "\n"
    r"        \label{tab:annotation-scheme-q4} \\"
)

DEFAULT_CAPTION = (
    "Annotation scheme for participant comments on Compar. Q7 "
    "(justifying decision for which translation is percieved as machine translation)."
)


def render_tex(codes: list[CodeRow], *, caption: str = DEFAULT_CAPTION) -> str:
    body = "\n".join(render_code_rows(codes))
    last_foot = TABLE_LAST_FOOT.replace("CPTN_PLACEHOLDER", caption)

    return (
        "% Auto-generated by build_annotation_scheme_Q4_table.py; do not edit by hand.\n"
        "% Requires: booktabs, longtable, array\n"
        "%\n"
        "% \\input{analysis/manuscript_tables/tex/annotation_scheme_Q4.tex}\n"
        "%\n"
        "% Reference examples: \\ref{M1}, \\ref{M9}, \\ref{M13}\n"
        "\n"
        "{\\footnotesize\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        f"\\renewcommand{{\\arraystretch}}{{{ARRAY_STRETCH}}}\n"
        "\\onecolumn\n"
        "\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}"
        "p{0.06\\textwidth} >{\\raggedright\\arraybackslash}"
        "p{0.14\\textwidth} >{\\raggedright\\arraybackslash}"
        "p{0.30\\textwidth} >{\\raggedright\\arraybackslash}"
        "p{0.24\\textwidth} >{\\raggedright\\arraybackslash}"
        "p{0.24\\textwidth}@{}}\n"
        f"{TABLE_HEADER}\n"
        "\\endfirsthead\n"
        f"{TABLE_CONTINUED_HEAD}\n"
        "\\endhead\n"
        f"{TABLE_CONTINUED_FOOT}\n"
        "\\endfoot\n"
        f"{last_foot}\n"
        "\\endlastfoot\n"
        f"{body}\n"
        "\\end{longtable}\n"
        "\\twocolumn\n"
        "}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate LaTeX annotation scheme table from coding_Q4.csv."
    )
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Input coding CSV (default: {DEFAULT_INPUT.name})",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output .tex file (default: {DEFAULT_OUTPUT.name})",
    )
    args = parser.parse_args(argv)

    if not args.input.is_file():
        print(f"error: input not found: {args.input}", file=sys.stderr)
        return 1

    codes = parse_csv(args.input)
    tex = render_tex(codes)
    args.output.write_text(tex, encoding="utf-8")
    print(f"Wrote {args.output} ({len(codes)} codes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
